{% set name = "deepdish" %}
{% set version = "0.3.7" %}
{% set sha256 = "6aff3abef693cec34438f183f29d1a2d9862aba27bb959d4f24d56e007e41ff3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: v{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - pytables

test:
  imports:
    - deepdish

about:
  home: http://deepdish.io/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Deep learning and data science tools from the University of Chicago.
  description: |
    The primary feature of deepdish is its ability to save and load 
    all kinds of data as HDF5. It can save any Python data structure, 
    offering the same ease of use as pickling or numpy.save.
  doc_url: http://deepdish.readthedocs.io/
  dev_url: https://github.com/uchicago-cs/deepdish

extra:
  recipe-maintainers:
    - basnijholt
    - gustavla
